# This is a basic workflow to help you get started with Actions

name: R Conda

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Create conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: recetox-xmsannotator-dev
          auto-update-conda: true
          environment-file: conda/environment-dev.yaml
          auto-activate-base: false
      - run: |
          conda init bash
          conda env list
      - name: Fetch batch1_neg test data
        run: wget -P tests/testthat/testdata/batch1_neg -i tests/remote-files/fetch_batch1_neg.txt
      - name: Fetch qc_solvent test data
        run: wget -P tests/testthat/testdata/qc_solvent -i tests/remote-files/fetch_qc_solvent.txt
      - name: Fetch sourceforge test data
        run: wget -P tests/testthat/testdata/sourceforge -i tests/remote-files/fetch_sourceforge.txt
      - name: Fetch qc_matrix test data
        run: wget -P tests/testthat/testdata/qc_matrix -i tests/remote-files/fetch_qc_matrix.txt
      - name: Run devtools::check()
        run: |
          conda activate recetox-xmsannotator-dev
          Rscript -e "devtools::check('.', error_on = 'error')"
